# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-28 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20181108_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='seller_location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='seller_number',
            field=models.IntegerField(null=True),
        ),
    ]
